Update npm-publish-github-packages.yml

diff --git a/.github/workflows/npm-publish-github-packages.yml b/.github/workflows/npm-publish-github-packages.yml
--- a/.github/workflows/npm-publish-github-packages.yml
+++ b/.github/workflows/npm-publish-github-packages.yml
@@ -1,7 +1,7 @@
 name: Build and Test React Application
 
 on:
-  # Triggers the workflow on push or pull request events in the main branch
+  # Trigger the workflow on push or pull request events in the main branch
   push:
     branches:
       - main
@@ -23,25 +23,33 @@ jobs:
           node-version: '14'  # Specify the Node.js version
 
       # Step to install dependencies
-      - name: Install dependencies
+      - name: Install Vlocity Build Tool
         run: |
-        npm install -g vlocity
+          # Install the Vlocity Build Tool globally
+          npm install -g vlocity
+        
+        # Verify installation
+        shell: bash
+        run: |
+          if ! vlocity-build -version &> /dev/null; then
+            echo "Failed to install or find vlocity-build."
+            exit 1
+          fi
 
-    # Verify the installation and check the path
-    vlocity-build -version || echo "Failed to install vlocity-build."
+      # Step to install application dependencies
+      - name: Install application dependencies
+        run: npm install
 
-# Step to build the React application
-- name: Build application
-  run: |
-    # Before running the build, verify the installation of vlocity-build
-    if ! command -v vlocity-build &> /dev/null; then
-        echo "vlocity-build command not found in PATH. Exiting."
-        exit 1
-    fi
-    
-    # Run the build command
-    npm run build
+      # Step to build the React application
+      - name: Build application
+        run: |
+          # Before running the build, verify the installation of vlocity-build
+          if ! command -v vlocity-build &> /dev/null; then
+            echo "vlocity-build command not found in PATH. Exiting."
+            exit 1
+          fi
+          
+          # Run the build command
+          npm run build
 
-      
-      # Optionally, you can add steps to deploy the built application if needed
-
+      # Add additional steps if you want to deploy the built application or perform other tasks
